version: '3.8'

services:
  web:
    build: .
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=${PGHOST}
      - USER=${PGUSER}
      - PASSWORD=${PGPASSWORD}
      - DB_HOST=${PGHOST}
      - DB_PORT=${PGPORT}
      - DB_NAME=${PGDATABASE}
      - DB_USER=${PGUSER}
      - DB_PASSWORD=${PGPASSWORD}

volumes:
  odoo-web-data: 