[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "odoo -c /etc/odoo/odoo.conf"
healthcheckPath = "/web/login"
healthcheckTimeout = 1200
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 